### ISSUE TITLE
Bug: Bad images in README

### ISSUE THREAD

**Issue by Masynchin** [timfi/dotmatrix#4]
### Description

As you mentioned in reddit post, pictures of matrix can be broken due to browsers "smart" behaviour. This problem is on README too

### Code

```python
Not the code, only ask for use picture in README
```

### Output

```plain
Will add picture in "Anything else?" section as I am not certain in posting picture here
```

### Anything else?

Example:
![image](https://user-images.githubusercontent.com/47028153/129638638-6274afb5-ab2b-4806-9a35-812c6fe7c733.png)

**Comment by timfi** [comment]
Hi, thanks for letting me know. This is a known issue mit many monospace fonts. It stems from the font renderer on your system and/or the font itself deciding that the empty braille characters (U+2800) should be kerned instead of preserving it's width. 

I'll add some images and a disclaimer/notice to the readme to address this.

**Comment by timfi** [comment]
As requested I've added some images and also included a disclaimer to the readme.
